language: java
jdk:
    -openjdk15
    addons:
      sonarcloud:
        organization: "lucafalasca"
        token:
          secure: "5d96ecaf001006a3c7885608471b6b5bb4b7e753" # encrypted value of your token

script:
    - ant build
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
    - sonar-scanner
