language: java
jdk:
    -openjdk15
    
    addons:
        sonacloud:
            organization: "LucaFalasca"
            token: "3e8faeeda763ef4bb766c5b329c2554a8b09854f"
script: 
    -ant build
    -sonar-scanner
